/*
 * Copyright (c) 2026
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RESET_RK3506_CRU_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_RESET_RK3506_CRU_H_

#define SRST_H_CAN0 212
#define SRST_CAN0   213
#define SRST_H_CAN1 214
#define SRST_CAN1   215

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RESET_RK3506_CRU_H_ */
