# SPDX-License-Identifier: Apache-2.0

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y

CONFIG_GPIO=y
CONFIG_GPIO_RK3506=y

# This application does not create an RPMsg endpoint.
CONFIG_SOC_RK3506_RPMSG_LITE=n
